[build]
  publish = "dist"

[[redirects]]
  from = "https://ybcarrelage.fr/*"
  to = "https://ybcarrelage.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ybcarrelage.fr/*"
  to = "https://ybcarrelage.com/:splat"
  status = 301
  force = true
